[package]
name = "raybow"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
png = "0.17.5"
gltf = {version = "1.0", features = ["KHR_lights_punctual"]}
rand = "0.8.5"